const COUNTRY_FLAGS: Record<string, string> = {
  'United States': '🇺🇸',
  'USA': '🇺🇸',
  'England': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'Scotland': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  'Wales': '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
  'Northern Ireland': '🇬🇧',
  'Ireland': '🇮🇪',
  'Australia': '🇦🇺',
  'South Africa': '🇿🇦',
  'Spain': '🇪🇸',
  'Japan': '🇯🇵',
  'South Korea': '🇰🇷',
  'Korea': '🇰🇷',
  'Sweden': '🇸🇪',
  'Norway': '🇳🇴',
  'Denmark': '🇩🇰',
  'Canada': '🇨🇦',
  'Argentina': '🇦🇷',
  'Chile': '🇨🇱',
  'Colombia': '🇨🇴',
  'Mexico': '🇲🇽',
  'Germany': '🇩🇪',
  'France': '🇫🇷',
  'Italy': '🇮🇹',
  'China': '🇨🇳',
  'Taiwan': '🇹🇼',
  'Thailand': '🇹🇭',
  'New Zealand': '🇳🇿',
  'Austria': '🇦🇹',
  'Czech Republic': '🇨🇿',
  'Belgium': '🇧🇪',
  'Netherlands': '🇳🇱',
  'Zimbabwe': '🇿🇼',
  'Fiji': '🇫🇯',
  'Venezuela': '🇻🇪',
  'Paraguay': '🇵🇾',
  'Brazil': '🇧🇷',
  'Dominican Republic': '🇩🇴',
  'Singapore': '🇸🇬',
  'Finland': '🇫🇮',
  'Switzerland': '🇨🇭',
}

export function countryFlag(country: string | null | undefined): string {
  if (!country) return ''
  return COUNTRY_FLAGS[country] ?? ''
}
